### ISSUE TITLE
Config file issues and suggestions

### ISSUE THREAD

**Issue by DixieTwixie** [Electrical-Age/ElectricalAge#145]
1. Typo in "copper" ("cooper").
2. There are 2 options for lead generation: one is "lead" and one is "plumb" which is short for latin "plumbum" which means lead too.
3. Please rename "mapgenerate" to "worldgen" since it is a common term.
4. Please rename config name to electricalage.cfg or something like that.

**Comment by taljaards** [comment]
Also, please add worldgen options for tin, platinum and silver?

**Comment by lambdaShade** [comment]
Quite old issue... thanks anyway !

@mbhalo
- Typo corrected with old config file auto-correction : https://github.com/Electrical-Age/ElectricalAge/commit/a98225ea5d64fe4d95e0ecd58b833fc3c3b2d5d7.
- "mapgenerate" doesn't change since that's not critical.
- The config file name doesn't change since this is the project codename.

@Mierzen
- Tin, platinum and silver... are you talking about this mod ? ;-)
