### ISSUE TITLE
Bug encontrado

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#162]
Alguns itens deste mod Electrical Age, esta afetando o nascimento dos mobs todos os mobs.
Exemplo:
Quando se coloca um item como o suporte de lampada no mundo, ou seja, no chão ele afeta o nascimento de mobs no local em um raio de 15 blocos mais ou menos.

Não testei com todos os itens, mas a maioria afeta o nascimento e mobs mesmo quando usado utilizado um ovo de mob como o de zumbi por exemplo mas isso acontece com todos os mobs, vacas porcos, etc...

Itens que testei: Fios e cabos, suporte para lampadas, turbinas termicas, painel solar e etc.

O que parece é que ao redor do item é criado um raio que não deixa os mobs nascerem.

Obrigado, gosto muito do mod e acho que deve ajudar.
espero que responda e resolva

**Comment by cm0x4D** [comment]
Thanks for issue, here the english translation (google):

Some items from this mod Electrical Age, is affecting the birth of mobs all the mobs.
example:
When you place an item as the lamp holder in the world, that is, on the ground it affects the birth of mobs in place within 15 blocks or so.

Not tested with all items, but most affects birth and mobs even when used using a mob egg as the zombie for example but it happens all the mobs, pigs cows, etc ...

Items tested: Wires and cables, support for lamps, Thermal turbines, solar panel, etc.

It turns out that around the item is created a distance that keeps the mobs were born.

Thank you, I like the mod and I think that should help.
I hope that answers and solve

**Comment by lambdaShade** [comment]
That's actually a functionnality, not a bug. But adding a command for control that isn't a bad idea... Noted.

**Comment by ghost** [comment]
Não acho que seja um funcionalidade por que se a luz estivesse acessa ae sim os mobs não spawnaria mas com a luz apaga os mobs spanw

**Comment by lambdaShade** [comment]
Now configurable via Eln.cfg or via the console (temp). See commit https://github.com/Electrical-Age/ElectricalAge/commit/835f3b1d2fa160f6cd2d607eb974c0f6a8d08230.
