### ISSUE TITLE
Itens Cabos devem ser alterados

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#169]
Os cabos estão representados de forma errada, para ser mais exato a bitola ou grossura dos cabos elétricos estão errados, por definição e propriedades elétricas reais quanto maior a grossura do cabo mais corrente o cabo suporta e quanto menor a corrente menos grossas são os cabos, então.

Cabos de 50V são mais grossos que de 200V e que são mais grossos que 800V que são mais grossos que 3200V.

**Comment by lambdaShade** [comment]
It's true that we can reduce the cable section with a voltage increase - for the same delivered power. But high voltage cables are not suspended lines, so the cable jacket must be increased for avoiding a breakdown because of insufficent dielectric strength. Higher voltage cables can drive more power too. So the higher apparent section for cables makes sense.
And finally, the use of very thick cables for powering some lamps is not really aesthetic ;-)
