### ISSUE TITLE
Circuits without crossing ground

### ISSUE THREAD

**Issue by serathius** [Electrical-Age/ElectricalAge#243]
I don't know how this collides with mod concept. But using DC double side grounded circuits is strange. Surly its makes everything simpler (only one cable to connect. simpler implementation), and maybe It would be enough for DC circuits, but if we wont to use capacitor and inductor then it should be fixed.

Currently every circuit built is basically connection of source to receiver through cables and return through ground with 0 resistance, additional connections just goes as parallel.

Solution:
Adding second connection to receivers
Giving earth high resistance
Adding colored 2 cable bundle with ability to simply split/merge.

**Comment by Dolu1990** [comment]
So fondamentaly, it's as you say, to keep things easier to connect. cube of 1 m^3 are not very efficient for complex wiring ^^
All become like in a Spice simulation, where designer put ground net where they want in place to wire all together by hand.

But the proposed change need loooooot of rework. maybe it not seem, but realy, it's eavy change.
I'm not hot XD.

But, what is realy the gain, to remove the magical ground ? in therme of possibilities (concrette possibilities) ?
You can already do DC/DC by using inductor ;)

**Comment by cm0x4D** [comment]
Do not like the idea of cables for grounds either for 2 reasons.

a) Wiring disaster: Already now the wiring can get quite tricky, if you have to wire all grounds together, oh my god, I rather would not like to think about..

b) The Mod is already complicated enough. If we add the complexity of ground cables and the maximal currents on them and the fact that grounds can be not on the same absolute voltage level and sometimes the references between them can float (if not connected), this would rather confuse people rather than making fun to play with it.

What is exactly the problem with capacitors and inductors with a ideal ground?
