### ISSUE TITLE
Harmonize power ratings w/RotaryCraft

### ISSUE THREAD

**Issue by Baughn** [Electrical-Age/ElectricalAge#250]
This should probably be an, oh, P4 or so--very low priority, but writing down while I remember.

Most mods use power scales that have no particular connection to reality. (An "RF"? How many RF to a Joule?)

However, EA and RotaryCraft are two mods that use real-world units; watts and joules. Unfortunately, they significantly disagree on how much energy a joule is. This can be seen by converting both to RF; the very lowest tier of RotaryCraft engine produce 1 kW, which converts to vastly less RF than 1 kW of EA power would.

Ideally they'd match up. I suspect @ReikaKalseki has already put some thought into his own units, which would mean rescaling EA instead.

@Baughn: Get back to this bug before playing with RotaryCraft integration.

**Comment by ReikaKalseki** [comment]
I think the real disagreement is on the size of 1 RF.

I now use the TE magma crucible and its rock melting as a baseline. I know from past research that it takes 5.2MJ to melt one cubic meter of andesite (this includes energy required to heat it), and that in TE this takes 240000RF by default for the magma crucible to do the same operation. From this, it is easy to calculate a basic conversion. Take note of the /20 factor because of tick vs second.

At the end, I get a value of 1RF/t = 520W. (Note the /t, since RF is a measure of energy, not power).

Also, I handle TE's configurability to some degree, using a bit of reflection into his config, which can be found [here](https://github.com/ReikaKalseki/DragonAPI/blob/master/ModInteract/Power/ReikaRFHelper.java).

For reference, all my power-conversion classes are here:
https://github.com/ReikaKalseki/DragonAPI/tree/master/ModInteract/Power

**Comment by Baughn** [comment]
So I did some calculations, while on vacation at the family cottage. It happens to have a 12V solar/battery power system.

We have a single pair of 12V batteries, totalling 410Ah, for a total of 17.7 MJ. Of course we can't use all of that energy if we want them to last, but...

The EA cost-oriented battery is 60 kJ. The capacity-oriented one, if I remember correctly, is 240 kJ, which is at least close to 1/60th of the real-world battery. My guess, therefore, is that the energy density is calculated from making them last the same number of _minecraft days_ as they would in real life.

Is this correct?

**Comment by ReikaKalseki** [comment]
One MC day is ten minutes, or 1/144 of a real day.

**Comment by cheesealmighty** [comment]
This might be a "necro", but I'm against opening new issues when the old ones aren't closed yet.

I wanted to ask if this was ever realized? Or in other words, was the compatibility between the shaft power and/or electricity of the two mods ever implemented? 

I'm aware of the fuel integration, that in essence provides 
RoC -> ELN (using ethanol).
RoC -> Railcraft Steam -> ELN
And a few other methods using RoC to create fuel and convert back to ELN power. Which is somewhat intuitive and acceptable.

I believe only way to do it the other way around is: 
ELN electricity -> ELN power converter -> RF -> RoC Magnetostatic engine -> RoC Shaft power.

Which is not really interesting, or fun, considering both mods provide really interesting mechanics that in theory should be compatible, while RF is... Game-y? It's which universal standard we ended up with, _I guess._

**Comment by jrddunbr** [comment]
There are configuration options in the config to allow balancing of ELN to
RF (and other units) in general, so you can balance it as you see fit,
using RF as the unit.

I think most forward progress right now is being focused on getting the mod
updated to 1.10 and beyond. Baughn does mention in the issue that it is of
relatively low priority. My guess is that it will be picked up at some
point after the major update is complete.

**Comment by cheesealmighty** [comment]
> There are configuration options in the config to allow balancing of ELN to
RF (and other units) in general, so you can balance it as you see fit,
using RF as the unit.

True, true, but I still see RF as a crutch to do things. I'd like to avoid it whenever possible. 

> I think most forward progress right now is being focused on getting the mod
updated to 1.10 and beyond. Baughn does mention in the issue that it is of
relatively low priority. My guess is that it will be picked up at some
point after the major update is complete.

This makes sense. While 1.7.10 is still alive (thanks to few other mods and ELN), a 1.12.2 version might be rejuvenation ELN needs. 

Edit: Although it should be added that there might not be a reason for this integration in 1.12,2 anyway, since in multiple occasions Reika expressed his disinterest in moving to version 1.12.2. and mostly focusing on maintaining 1.7.10 version of the mod. Unless he's doing something behind the scenes, I don't think this has changed.

**Comment by ReikaKalseki** [comment]
I do not want a direct converter into RC power that I do not control. It is guaranteed to cause exploits if I change ratios - as I have done many times before - or if I decide on balance changes on my end.

**Comment by cheesealmighty** [comment]
> ELN electricity -> ELN power converter -> RF -> RoC Magnetostatic engine -> RoC Shaft power.

What I'm suggesting here is taking out this part:
>  -> ELN power converter -> RF -> RoC Magnetostatic engine -> 

and condensing it into one single machine (Similar to pneumatic/EU/RF converters already present in RoC). 

And balancing around the fact that:
> Most mods use power scales that have no particular connection to reality.

While these two mods do. 

And while Electrical Age doesn't accept other mods' power, a special case might be made for Rotarycraft, from what I understand.

**Comment by ReikaKalseki** [comment]
> While these two mods do.

Maybe, but that is no guarantee the numbers will mesh nicely, not in a way conducive to good game design or balance.

**Comment by cheesealmighty** [comment]
> Maybe, but that is no guarantee the numbers will mesh nicely, not in a way conducive to good game design or balance.

This doesn't say it'd be impossible though. 

The challenge in ELN seems to be mostly about management of electricity, rather than the creation of shaft power.  

And the challenge in RoC is about generating the shaft power itself.

If you were to say, make RoC shaft power to ELN shaft power possible, but not the other way around,
and also make ELN electricity to RoC shaft power possible (with appropriate gating, of course). This wouldn't be much dissimilar to what Electricraft motors are doing anyway, as far as I know.

It'd create an interesting environment to build in. Unless I'm missing a very obvious thing.

Edit: 
> The challenge in ELN seems to be mostly about management of electricity, rather than the creation of shaft power.

This deduction comes from the fact that you can feed any of the fuels from the game to its generators, and it'll accept it. And as far as how their behaviour go, RF = Oil/Ethanol/Steam (i.e. stored in a container, easily transported with a tube).

**Comment by Baughn** [comment]
Management of shaft power is still relevant, given they can overspeed, but...

This issue is effectively obsolete. Eln is leaving 1.7 behind, and I believe Reika has stated that RoC will never do that. So conversion is no longer a possibility.
