### ISSUE TITLE
Gostei, bom trabalho! - ELOGIO

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#260]
Cara, gostei bastante da atualização esta bem melhor o desempenho e a simulação.

Mas como todo elogio vem seguido de uns pedidos, XD

É mais para a estética do mod e a logica também, corrija os cabos por que os cabos de baixa tensão devem ser o mais grosso e os de alta tensão tem que ser o mais fino.
Por que a bitola do cabo é definida devido a corrente que passa nela, lei de 2º ohm assim a tensão é maior mas a corrente é menor logo o cabo é sempre mais fino.

Já um dos "Comentarios" sobre colocar dois fios isso ja não é tão possivel mas da para relever.

**Comment by yannic312** [comment]
here the english Version (translated by Google translate): 
Good, good job! - COMPLIMENT

Man, I really liked the update this better performance and simulation.

But like all praise is followed by a request, XD

It's more for the aesthetics of the mod and the logic also fix the cables that low voltage cables should be as thick and high voltage has to be the finest.
  Why Cable size is defined because the current through it, of 2 ohm law so the tension is higher but the current is less then the cable is always thinner.

Already one of the "Comments" about putting two wires that already is not as possible but for the relever.

**Comment by cm0x4D** [comment]
People got used to the cables. Higher voltage -> thicker isolation needed. So we probably won't change this.
