### ISSUE TITLE
Add resistors

### ISSUE THREAD

**Issue by Baughn** [Electrical-Age/ElectricalAge#265]
For many purposes. Inrush current limiters, generation-shedding to ground, etc. etc...

They're the sole missing fundamental circuit element, and I will have it. How hard do you think it would be to add them? I'm willing to give it a try, though I haven't had much time to work on EA yet.

I'm imagining an UI with two slots. One for a cable, to select the voltage; another for coal dust, to select the resistance.

**Comment by lambdaShade** [comment]
Hello Baughn,
I've already done the resistor 3D model one year ago (see "PowerElectricPrimitives.blend"), but effectively the integration is still pending. I fully agree with your UI proposition.
Since nobody hasn't really a lot of time to allocate on the project, I suggest that the first free person makes the integration. ;-)

**Comment by Baughn** [comment]
I'm giving it a shot.
