### ISSUE TITLE
DAYLIGHT SENSOR NOT PROPERLY WORKING

### ISSUE THREAD

**Issue by CarolAnthony** [Electrical-Age/ElectricalAge#286]
I CREATE NEWORLD THEN I build DAYLIGHT SENSOR and high voltage relay connedted in 200v turbine and heat furnace and then i build lamp supply , 3 street light after a NIGHT THe streetlight not Turning ON Automaticaly  WHY ?

**Comment by ghost** [comment]
Eu entendi muito pouco o que vc escreveu poderia mandar um printscreen? talvez poderia ajudar, as vezes não é bug ou erro do mod. =D

**Comment by nonnodacciaio** [comment]
You have to set the relay on normally closed

**Comment by CarolAnthony** [comment]
i know but some time it will not work

**Comment by ghost** [comment]
Ola carol Anthony, agora entendi o problema. Para ajudar tem este vídeo, além de eu mostrar geração de energia por paneis solares e como carregar baterias tem a parte do sensor de Luz Natural, o seu problema é que junto com o sensor precisa de um processador de sinal.
Não sei se vc entende português, mas assista o vídeo que só vendo e reproduzindo como teste no seu mapa de minecraft, creio que você vai entender.

Vídeo: https://www.youtube.com/watch?v=Q4w4oeSLd-A

**Comment by cm0x4D** [comment]
The sensor's output voltage is an analog signal that is proportional to the daylight intensity and not a digital signal to control a relay. You have to condition the signal in order to detect if it is day or night using a signal processor and using a custom threshold.

Lets assume you take input A of the signal processor for the daylight sensor input, you would need the formula **A > 0.1** to change the  relay output at 10% of the daylight intensity.
