### ISSUE TITLE
Diodes are exploding when i put them to my Powergrid!

### ISSUE THREAD

**Issue by Domi1993** [Electrical-Age/ElectricalAge#332]
Im just wondering why diodes are exploding when i put it in my 160V Power cable, and additional informations about Diodes when holding shift are missing lile the max. Reverse Voltage and current.

I think the Power turbines are working on DC it makes sense because batteries are deliver DC but what is about the Transformers? They can't work on DC the mod is cool but a little bit confusing for me because i'm Electrician the mod is contradicting the electrical Rules.

How i can imagine this things are working?

It will be nice when there are some AC/DC and DC/AC converters to attach them to my Solarpanels (DC)

**Comment by Baughn** [comment]
The entire mod is DC; there is no AC anywhere. The mental model you should be using is that cables include both a live and a neutral wire, though some devices (batteries..) allow you to connect several in series.

The transformer model is confusing, yes. Replacing it is somewhere in the TODO list, but you should think of it as a two-way buck/boost converter. As for solar panels, you can connect them directly, but they're one of the series-mode devices and need an explicit ground.

Diodes break because of a bug, which I believe is already fixed and will be in the next release.

For any further questions, please try #electricalage on irc.rizon.net as well...
