### ISSUE TITLE
Community and support

### ISSUE THREAD

**Issue by metc** [Electrical-Age/ElectricalAge#349]
I see several options we could use to add a discussion platform or similar. We only have an IRC channel now and maybe we should setup other ways to communicates or to ask support.

Here are some options I think about:
1. IRC as available now
2. Google group
3. Gitter chat (https://gitter.im/)
4. Discourse discussion platform (http://www.discourse.org/)
5. Slack messaging (https://slack.com/)
6. HipChat (https://www.hipchat.com/)

@Electrical-Age/admin and @Electrical-Age/devs what is your opinion about adding a such platform ? Which one best fits our needs ?

**Comment by cm0x4D** [comment]
What about https://www.odoo.com/de_DE/page/community-builder or http://www.osqa.net

**Comment by lambdaShade** [comment]
Hmm... For what purpose precisely do you want to use another forum/chat ? Users<->Users or Devs<->Devs or mixed ? It's not clear...
For support, this is already quite redundant : GitHub issues (best place for bugs/requests), IRC, Minecraft forum (best place for user tricks).
Maybe the redaction of the wiki content is a bigger priority, because it will solve min 1/3 of the user's questions ?

**Comment by cm0x4D** [comment]
I would actually prefer a forum or Q&A solution for Users vs Users support. A lot of Minecraft users might have a hard time using IRC if they even know what it actually is. I see IRC rather for communication between Devs...

**Comment by metc** [comment]
Odoo and Osqa are based on the Stackoverflow model. They could be both a good alternative.
Osqa is open-source and based on Python. I do not known if I can install it on an Apache shared webserver...

**Comment by metc** [comment]
Atlassian offers free licences for many of their products, like JIRA, Confluence, HipChat, etc.
Should we request an open-source license ? https://fr.atlassian.com/software/views/open-source-license-request

For instance, for the wiki, we currently use MediaWiki. It is well known by many user and project contributors. Confluence can be an alternative with more features... JIRA can be really interesting for Agile software development and bug tracking.

**Comment by Baughn** [comment]
I'd advice against switching the wiki. The feature set and syntax changes, and as you say, people already know Mediawiki.

**Comment by cm0x4D** [comment]
Issues on github are sufficient IMHO. 

Personally I would prefer Confluence over MediaWiki, but we could ask the people contributing to the wiki what they actually prefer...

**Comment by ghost** [comment]
Confluence is not open source. https://www.youtube.com/watch?v=4F4qzPbcFiA [1].  Mediawiki has my preference. (especially since we already have it) . 

I'd very much like to see more people adding pages to it though. Click on a red link today and fill something in, doesn't have to look pretty. Plain text is fine.  If you don't have an account, feel free to ask for one here or anywhere.

<s>Incidentally, what's the official IRC channel? It isn't listed on the wiki (yet) ;-)</s> (Fixed)

In other news, did someone say a better server was needed?

[1] I'm an open source pragmatist. If we've been here once we've been here a hundred times; people just never learn.

**Comment by Baughn** [comment]
Regarding forums...

I don't know that we have a large enough user base to _need_ it, but at the same time, almost anything other than minecraftforum.net would be nicer. The only problem is, a lot of players are already there, so we can't really abandon it.

Almost anything else would be nicer, though. Minecraftforum _sucks_.

The only alternatives I'm familiar with are Xenforo and SMF. The first one is probably out; it's a good one, but inexpensive for what's basically a nice-to-have. SMF has a "social network login" mod, however, which would take away the need for people to register. That increases the chance of it being used, ever.

Thoughts?

**Comment by cm0x4D** [comment]
The need for a github account to report bugs or post new ideas is not optimal. Maybe this might be a solution: https://gitreports.com? If users do not need to create an account, they will probably report bugs more frequently...

**Comment by Baughn** [comment]
I've been thinking about an in-game command that would look for Eln blocks within (say) 10x10x10 of the player, then trace out the network and upload the graph to one of our servers, which could then produce a schematic using graphviz or something.

No idea when I'd ever get around to something like that, though.

**Comment by metc** [comment]
Gitreports is really easy to setup and users can post comments or bus with ease. Should we add a link on the website ? I vote up.

**Comment by lambdaShade** [comment]
@metc Good idea if you personally take time to read the extra count of issues (including easy (near-)spamming posts) and correct them. Otherwise, just no : we don't have such time.

**Comment by Dolu1990** [comment]
I agree that Minecraft forum sucks.
Github discourage pointless issues <3 (because it need an account)

**Comment by cm0x4D** [comment]
Discussion is on #405...
