### ISSUE TITLE
Electrical Age Crashing

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#392]
When ever I go into MC and open it. The Mod crashes.

Issues:
1) Tutorial Map will not show
2) When ever opening other world, mod crashes
3) Tried on different 1.7.10 forge versions, result = crash

Recommended version of 1.7.10 forge.
1.10 Electrical age
and 1.10 Tutorial mod.

I am giving the crash report as well.
Please help.
[crash-2016-01-22_11.23.44-client.txt](https://github.com/Electrical-Age/ElectricalAge/files/101185/crash-2016-01-22_11.23.44-client.txt)

**Comment by cm0x4D** [comment]
Strange, Minecraft is not crashing inside code of Electrical Age.

Can you check the content of the folder ~/Library/Application\ Support/minecraft/mods?

I once had a similar problem and it was caused by two different versions of the mod. If there are more than one Electrical Age jar, delete all old ones.

**Comment by ghost** [comment]
I fixed it by deleting any forge version and reinsyltalling. But thanks for your help.

**Comment by ghost** [comment]
My friend had to reinstall Minecraft altogether.
