### ISSUE TITLE
Can't find how to remotley find battery level

### ISSUE THREAD

**Issue by redstonegenious** [Electrical-Age/ElectricalAge#424]
I want to make a circut that makes me able to read my battery level in the machine room. But i cant find a cirut that'll allow me to do so. I am using four batteries in series and five in paralell. The output is 50v per batterie. If you must know, i am using a glitch that allows me to charge single use batteries.

**Comment by Baughn** [comment]
I'm hardly going to object to that; you play the game the way you want. Don't rely on that glitch remaining in future versions, though. :P

To measure the level of a battery, you need to understand about open-circuit vs. closed-circuit voltages. Yes, if you right-click the battery you'll get an exact percentage; that's a convenience feature, and one I have no intention of making accessible to in-game automation.

Open circuit voltage is the voltage the battery will show if you have no load on it. There's a batteryCharge function in the signal processor which can convert the open-circuit voltage (as a fraction of nominal voltage) to a charge percentage. E.g, if you have a 50V battery, then you could use this logic:
- Use a voltage probe set to 0 to 100V.
- Feed this into a signal processor, coded to `batteryCharge(A / 2)`.
- The output will be the charge level of the battery, assuming an open circuit.

The division is there because the signal processor can only output 0-1, and the battery voltage will be above 50V when it's charged above, oh, 40% or so. So use a larger range, and divide.

Once you've figured out all this, you can start trying to convert closed-circuit (battery under load) voltage to open-circuit voltage. One warning--this is not going to be easy, or at least it requires some algebra. You'll need to read http://www.facstaff.bucknell.edu/mastascu/elessonshtml/source/source2.html.

But I recommend getting the open-circuit charge readout first.
