### ISSUE TITLE
(Suggestion) Mod reverse compatibility

### ISSUE THREAD

**Issue by melindaendv** [Electrical-Age/ElectricalAge#518]
When I say reverse compatible I mean able to connect via an adapter to other power systems mods in both directions like: Immersive engineering connectors, IC2 cables, Buildcraft pipes, Thermal expansion ducts, Ender IO conduits and Galacticraft wires.
having different adapter blocks that will convert the connections would greatly expand this mods usability especially in servers that are using multiple mods that have power systems in place prior to adding this mod.
Of course you would have a section in a config to enable or disable these converters to keep the mod genuine.

**Comment by bloxgate** [comment]
See #223 #273 #264 
It seems like they have no intention what-so-ever of adding a converter in the other direction.

**Comment by Baughn** [comment]
It won't happen, because all the fun of EA is in power generation. There's very little to do with the mod _other_ than generate power, but once you learn to do so at scale it's some of the best fun you can have in Minecraft.

Admittedly this will work better once the utility poles are merged, but it _does_ have a role in tech packs. EA trades resource cost for difficulty: it's relatively cheap to generate thousands of rf/t with it, and even uses somewhat less fuel than the norm, but good luck doing so on your first try without explosions.

(I recommend turning those off, by the way. I should make that the default.)

What would be a single furnace generator block in other mods, is broken out into a large power plant in EA. And getting it working is such a great sense of accomplishment, not to mention that I still haven't tried all possible combinations that might work. They all have something different going for them. None of it is hardcoded; this is all emergent behaviour.

So, no. We will not be adding an other-to-Eln converter.

Can I recommend the steam turbine?
