### ISSUE TITLE
ColoredLightsCore Mod Compatibility

### ISSUE THREAD

**Issue by Cagtay3346** [Electrical-Age/ElectricalAge#522]
I want to use Hi everyone I coloredlightscor Mode but not compatible with this mode and bugs occurs ie cables, lamps, it's sensors are invisible and I am glad you are correct that my work is difficult or you would be glad if you add colored lights next date herein. colored lights are always good :) 
http://hizliresim.com/gXMJRL

**Comment by Baughn** [comment]
It's not going to happen, least not in the 1.7 cycle. Colored Lights alters the Minecraft renderer in ways that would be extremely difficult to deal with, and in any case I'm gearing up for porting EA to 1.10.

Doing the port may make it work on its own, due to changes in 1.10. If it doesn't, I'm still not going to spend time on it.
