### ISSUE TITLE
BindException: Adress already in use

### ISSUE THREAD

**Issue by gwen1230** [Electrical-Age/ElectricalAge#523]
I try to use your mod on a server (OmgServ) but when I launch my server I got a BindException: Address already in use.... I haven't this error when I remove ElectricalAge and this is the only mod activated. Can you help me ?

**Comment by cm0x4D** [comment]
Hi gwen,

This is caused by a bug that starts the Modbus server even if deactivated (which is the default) so the mod does not run twice on the same machine as it tries to start a TCP socket listening to the port 1502. 

A simple fix: In the file **Config/Eln.cfg** change **I:port=1502** to another number (>1024) and it should work. The next release will fix that bug.

**Comment by gwen1230** [comment]
I try to change this in the config file (section modbus) but this doesn't change anything... The listening port is still 1502

EDIT : After downloading the source code, I think the port configuration isn't retrieve. This is the default constructor of ModbusTCP which is used.

**Comment by cm0x4D** [comment]
Sorry, my bad. The port is not yet configurable in the last release, the best would be to get a development snapshot of version 1.12.0 from here: http://ci.safranil.fr/job/ElectricalAge/lastSuccessfulBuild/

This should fix the issue. The release is pretty close, so the snapshot should be quite stable.

**Comment by gwen1230** [comment]
Thanks ! It works
