### ISSUE TITLE
Crash on Client r17

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#56]
When launching without computercraft mod installed in the client, it crashes. Server runs normal without crash.
Crash report
http://pastebin.com/yD2VDfRc

**Comment by Dolu1990** [comment]
Hi,
It's very strang because i very rarely have computer craft instaled, and every time when i do a release i test the jar without computer craft instalated, and there is no crash. I juste have test now, there is no crash.
Hmmmmm it's strang.
But that has give me a idea XD 
I think i must add into code that the Computer craft probe IO block is only loaded if there is computer craft jars classes are detected by reflexion.
That come in one of next update :)

**Comment by Dolu1990** [comment]
R18 released, that probably solve your issue.
Could you give me feed back about that ?
thanks :)

**Comment by ghost** [comment]
I will check it tonight and let you know.

**Comment by ghost** [comment]
Confirmed resolved. Client now launches successfully without Computercraft. Closing issue.

**Comment by Dolu1990** [comment]
: D
Thanks for issue :)
