### ISSUE TITLE
Conflict with Ridable Spiders

### ISSUE THREAD

**Issue by Techokami** [Electrical-Age/ElectricalAge#59]
Quite simply, if you have Ridable Spiders and this mod both installed at the same time, [this happens.](http://pastebin.com/nf0Ke59q)
This issue is also being reported to the author of Ridable Spiders.

**Comment by Dolu1990** [comment]
hi,
I think it's a Ridable Spiders issue, because in electrical age, id reserved for replicator entity is replicatorRegistrationId = EntityRegistry.findGlobalUniqueEntityId();

To solve this kind of issue i have add into Eln.cfg the possibility to manualy assign a id to replicator entity.

If it's -1 => that use EntityRegistry.findGlobalUniqueEntityId();
else that get the number that you put as id.

Maybe i must put the default id in Eln.cfg, at 30621 (for example)?
