### ISSUE TITLE
Sounds are crashing Game

### ISSUE THREAD

**Issue by Domi1993** [Electrical-Age/ElectricalAge#609]
I Built a Gasturbine Powerplant, it works nice but when the gasturbine has reached it speed. And then i shut down the Turbine will cause a crash of Minecraft (see Crash report).

Specially it crashes only when the shaft speed is going below arround 100 rad/s i restarted the Turbine once from higher than 100 rad/s and the game wont crash.

When the Turbine was never running, the game don't crash. But when it was running and slowed down below 100rad/s, the game crashes even when it is on 800rad/s

Crash Report:
[http://pastebin.com/LZNeHrHU](url)

I Used the Release from Erisia 14 to test this crash

**Comment by Domi1993** [comment]
Sorry but the last part was wrong, the game isn't crashing anymore, when the turbine runs on 800rad/s. (I don't test it for longer time but it crahses on low speed at the same time as i enabled the sounds)

**Comment by cm0x4D** [comment]
@Domi1993 Could you check with the feature branch #617 if it still happens? I was not able to reproduce the bug...

**Comment by Domi1993** [comment]
I'll try it when i have time for it. Reproducing the crash on another world would be helpfull, to check if my world causes the crash

**Comment by cm0x4D** [comment]
Ok, now I had it too. This happens when there are too many sounds playing at the same time. I had a ton of replicators around me and then the game crashed. 

It seems that you can queue a loop for playing and independent if the sound could get actually played or not, it will be added to a map in MC. The problem is that the isSoundPlaying() method only returns true if the sound is effectively played. So in the case the sound could not be played we tried to add it again to the same map and earned an exception for that. I just added code that handles this exception, so now it should not crash the game anymore.

It would actually help if you can do some tests with #617 to see if it is really fixed.

**Comment by Domi1993** [comment]
Ok I'll try it next week, then i have time for it

**Comment by Baughn** [comment]
This happened to me, with the latest build~~

http://sprunge.us/bXbI

Specifically, when I pickaxe'd a plate machine that *wasn't playing the sound it's supposed to*. Which makes it sound like the start-playing packet got lost, or something.

**Comment by Baughn** [comment]
I think https://github.com/Electrical-Age/ElectricalAge/pull/631 probably fixes this.

**Comment by Domi1993** [comment]
My gasturbine crash is now fixed
