### ISSUE TITLE
Server join kick

### ISSUE THREAD

**Issue by ArcasCZ** [Electrical-Age/ElectricalAge#624]
After login getting this error.

http://pastebin.com/rvbsMf6v

**Comment by cm0x4D** [comment]
What version of EA, MC and forge do you use?

**Comment by ArcasCZ** [comment]
EA: 1.13.0
Forge: 1614
MC: 1.7.10

**Comment by cm0x4D** [comment]
Did you use the very same version on server and client? It seems that the client is not able to instantiate a render object for a given element. Or do you know which item was placed bevor the problems started?

**Comment by ArcasCZ** [comment]
Yep, same version. It was fuel_heat_furnace.name

**Comment by cm0x4D** [comment]
Fuel heat furnace was not in 1.13.0. So it is definitely not that version.

Do you run a snapshot on the server?

**Comment by ArcasCZ** [comment]
Yep, 'cause of another error. You should definitly mark Snapshots with some mark :D

**Comment by AMIDIBOSS** [comment]
Let me ask: do you have any other mpds?

**Comment by AMIDIBOSS** [comment]
*mods
I've seen lots of problrms like this, you shall try:
DO A BACKUP before trying anything. And i take no responsibility if you happen to break something. 
-try generating a new world
-try changing username/log in with diffrent account
-download the latest snapshot both on client and server. 
-remove any other mods. DO IT ON NEW WORLD!! 
And once again, don't forget to backup! 
This shall help

**Comment by ArcasCZ** [comment]
I use EA in modpack, so... Yep, there are plenty of mods. And nope, I can't test like this, 'cause I have pre-generated map at 10 000 of blocks, so backup will take a lot of time. Also, creating another acc and trying those stuff is useless.

We tried it simply - my friend placed block, I joined and get kicked. Then he destroyed it and I can connect. He placed it againd and I was kicked. So yep, it's problem with that block.

**Comment by Baughn** [comment]
Apropos of nothing, if you have root access to your server you should try ZFS snapshots. They're every bit as good as backups, but take a fraction of a second and very little disk to make, because the filesystem keeps track of what changes between snapshots.

On the Eln dev server I take snapshots every half-hour, and keep them forever. That's about 100MB per snapshot, in practice. It correlates to player activity, but not world size; unchanged chunks don't take up space in the backup, though the world is about 5GB.

(Though while disk is cheap, it's on SSD so I delete them after two weeks on the server. They're kept forever on a backup system.)

**Comment by ArcasCZ** [comment]
I don't have so much disk space. Also, I have some experiences with Java and modding and I know, that those informations leads to problem with specific block.
