### ISSUE TITLE
Exploding cables bug?

### ISSUE THREAD

**Issue by bjorguv** [Electrical-Age/ElectricalAge#685]
http://imgur.com/a/1VPhB (gallery scroll down)

the cables are exploding idk why.

**Comment by AMIDIBOSS** [comment]
How much lamps do you wanted to power?

**Comment by cm0x4D** [comment]
The cause is overheating by a current higher than the cable limit. Farming lamps consume a lot of energy, you may want use other bulps if you not want to grow plants or power the lamps with more than 1 lamp supply. 

There is a Universal Meter that shows you the voltage, current and temperature of the cables if you need zo check the installation.
