### ISSUE TITLE
Advanced converter

### ISSUE THREAD

**Issue by AMIDIBOSS** [Electrical-Age/ElectricalAge#736]
I think we shall have more expensive, end game, 16:1 ratio converter.
Instead of placing two 4:1 ratio transformers.
Ground and polemount. I'd be glad if that's possible.

**Comment by OmegaHaxors** [comment]
I support this in the form of a type of variac. Building auto-converters in world is absolutely terrible even though it's possible; due to the voltage and amperage limits on the wires, either the primary fails due to over-amping or the secondary fails due to over-volting and there's no reliable way to remedy that.

I would prefer the wires be improved to allow this to be possible, but it's probably easier to balance to simply make it as a new block which can be manipulated by signals.

**Comment by AMIDIBOSS** [comment]
I didn't meant variacs, but hey are a good idea, too

**Comment by Baughn** [comment]
Duplicate of #749
