### ISSUE TITLE
Missing/incorrect names for utility poles.

### ISSUE THREAD

**Issue by DonBruce64** [Electrical-Age/ElectricalAge#771]
![2017-09-30_23 08 49](https://user-images.githubusercontent.com/15241611/31051691-c9ad8b16-a634-11e7-829c-bb75a7a1d57a.png)
![2017-09-30_23 09 19](https://user-images.githubusercontent.com/15241611/31051693-d3cee4fa-a634-11e7-8cef-22c1eebcb8e3.png)

**Comment by OmegaHaxors** [comment]
Don't worry, they're fixed in the development version. Expect the proper names and descriptions when the official update rolls. Thanks to a bit of development hell, it might take a little of time so please be patient.

Related spoiler alert: The next update is going to include powerline towers and mains converters.

**Comment by AMIDIBOSS** [comment]
The lang file lacks words for utility poles.
