### ISSUE TITLE
[idea] galaticraft

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#834]
you guys should add galactic craft its such a good space travel mod and sorry for posting in the wrong section i've never used github before.

**Comment by jrddunbr** [comment]
That should go in the IRC channel #erisia on Rizon if it's about the Erisia
Minecraft server. This issue tracker is for issues with the source code
that runs the Electrical Age mod, and is not really a good place to ask for
that.

On Jan 11, 2018 7:43 AM, "Tronkvis" <notifications@github.com> wrote:

you guys should add galactic craft its such a good space travel mod and
sorry for posting in the wrong section i've never used github before.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Electrical-Age/ElectricalAge/issues/834>, or mute the
thread

**Comment by ghost** [comment]
thank you for your help
