### ISSUE TITLE
Help!. Intergration with computercraft

### ISSUE THREAD

**Issue by J09** [Electrical-Age/ElectricalAge#869]
Hi I need help I put a voltage probe and connected it to the ELN computer probe. I figured out how to measure the exact volts by multiplying by 100. I get the exact volts the voltage on the uni-meter shows 287V but on the computer when I print the volts it shows up like this “28.7(other random numbers)” how can I get rid of that then make it print like this “287”

**Comment by jrddunbr** [comment]
That doesn't sound like a Electrical Age problem. That said, try rounding after multiplying by 10.

http://www.computercraft.info/forums2/index.php?/topic/10189-rounding/

**Comment by Grissess** [comment]
If you want a string, use `string.format`:

```
> string.format("%.0f", 287.45198)
287
> string.format("%.0f", 3691.25346)
3691
```

(Although it's not clear, those are all strings.) It also has a number of other nice goodies for display purposes, like fixed-width fields, alignment, fill characters, and so forth, which is quite nice if you're going to be printing out tabular data so that everything is nice and even.

If you just want an int, use `math.floor`:

```
> math.floor(287.45198)
287
> math.floor(3691.25346)
3691
```

Bear in mind that some precision is lost from here on, so do this only at the end of all other calculations.

**Comment by J09** [comment]
One more problem it shows up like this “28” but not “287” like I wanted it too again it showed up like this before “28.784838”

**Comment by J09** [comment]
Any math tricks?

**Comment by J09** [comment]
Never mind got exactly what I wanted :) multiplyed it by 1000

**Comment by J09** [comment]
Thanks for the help

**Comment by Grissess** [comment]
Sounds like you just need to multiply your input by 10, as @jrddunbr mentioned above :)

EDIT: Oh, shoot, the comments desync'd. Glad it worked out!
